### ISSUE TITLE
use `python_package_requires_python` as the default for `docker_python_version`

### ISSUE THREAD

**Issue by bjhardcastle** [AllenInstitute/copier-pdm-npc#1]
It makes sense (to me) to use the same setup as on github actions
https://github.com/AllenInstitute/copier-pdm-npc/blob/main/project/.github/workflows/publish.yml.jinja#L27-L32

**Comment by mochic** [comment]
@bjhardcastle That value can be >=3.9 or the other various conventions that pdm supports. jinja2 appears to support slicing but not regex for variables. There could be a more complex solution using jinja2 extensions but I figured simpler would get the job done and potentially be more stable. If we could somehow use copier or pdm to know our python version (might not be possible or easy) that would be way better.

**Comment by bjhardcastle** [comment]
Ah I see, the Dockerfile doesn't use the same syntax.. then I agree it's not worth parsing the version number.
